import = ["/Users/craigoconnor/.config/alacritty/catppuccin-frappe.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = false

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "Hack Nerd Font"
style = "Bold"
# family = "Cascadia Pro"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300

# [mouse.triple_click]
# threshold = 300

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

# [shell]
# args = ["attach", "-c", "main"]
# program = "/Users/craigoconnor/.cargo/bin/zellij"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
opacity = 1.0
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 160
lines = 48

[window.padding]
x = 0
y = 0
